---
- hosts: all
  tasks:
  - name: Create a group of all hosts by operating system
    action: group_by key={{ansible_distribution}}-{{ansible_distribution_version}}

- hosts: testing-director
  sudo: yes
  tags:
    - director
  roles:
    - common
    - dir-client
    - director

- hosts: testing-storage
  sudo: yes
  tags:
    - storage
  roles:
    - common
    - storage

- hosts: testing-almir
  sudo: yes
  tags:
    - almir
  roles:
    - common
    - almir
