---
- apt: pkg={{ item }}
  with_items:
    - git
    - bacula-console
    - python-setuptools
    - gcc
    - python-dev
    - wget

# almir user should be bacula according to the documentation
# http://almir.readthedocs.org/en/latest/userguide.html#installer-interactive
- user: name={{ almir_user }}

- file: state=directory path={{almir_dir}} owner={{almir_user}}

- file: state=directory path=/tmp/almir owner={{almir_user}}

- copy: src=pre_almir.sh dest={{almir_dir}}/

- copy: src=post_almir.sh dest={{almir_dir}}/


- command: bash pre_almir.sh chdir={{almir_dir}}

- template: src=buildout.cfg dest={{almir_dir}}/buildout.cfg

# tmp fix https://github.com/iElectric/almir/issues/63
- command: sed -i 's/pg8000 = 1.09/pg8000 = 1.9.2/' {{almir_dir}}/buildout.d/versions.cfg

- command: bash post_almir.sh chdir={{almir_dir}}
